analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  
  errors:
    missing_const: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore

linter:
  rules:
    # 关闭最严格的规则
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    unnecessary_const: false
    
    # 保持一些有用的规则
    avoid_print: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true